=== casszhao/ReAGent/docs/rationalization.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Rational results",
    "description": "Rational results from experiments",
    "type": "object",
    "properties": {
        "id": {
            "type": "number",
            "minimum": -1
        },
        "input-text": {
            "description": "Text corresponding to input-tokens",
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "input-tokens": {
            "description": "Tokens of the input sequence",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 0
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "target-text": {
            "description": "Text corresponding to target-token",
            "type": "string"
        },
        "target-token": {
            "description": "Target token to predict from the input sequence",
            "type": "number",
            "minimum": 0
        },
        "importance-scores": {
            "description": "Importance scores of each token in the input sequence",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "rational-size": {
            "description": "Size of the rational. Define how many items in the rational-tokens.",
            "type": "number",
            "minimum": 1
        },
        "rational-positions": {
            "description": "Positions of tokens of input which included in the rational",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 0
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "rational-text": {
            "description": "Text corresponding to rational-tokens",
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "rational-tokens": {
            "description": "Tokens included in the rational",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 0
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "comments": {
            "description": "Additional comments",
            "type": "object"
        },
        "trace": {
            "description": "Trace of the process",
            "type": "object",
            "properties": {
                "importance-scores": {
                    "description": "Trace of importance scores",
                    "type": "array",
                    "items": {
                        "description": "One stage of importance scores",
                        "type": "array",
                        "items": {
                            "type": "number",
                            "minimum": 0,
                            "maximum": 1
                        },
                        "minItems": 1,
                        "uniqueItems": false
                    }
                },
                "target-likelihood-original": {
                    "description": "Target likelihood with the original sequence",
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                },
                "target-likelihood": {
                    "description": "Trace of target likelihood with rational not replaced",
                    "type": "array",
                    "items": {
                        "description": "One stage of target likelihood with rational not replaced",
                        "type": "number",
                        "minimum": 0,
                        "maximum": 1
                    }
                }
            },
            "required": [
                "importance-scores",
                "target-likelihood-original",
                "target-likelihood"
            ]
        }
    },
    "required": [
        "input-text",
        "input-tokens",
        "target-text",
        "target-token",
        "rational-size",
        "rational-positions",
        "rational-text",
        "rational-tokens"
    ]
}

=== casszhao/ReAGent/rationalization_results/analogies/gpt2_xl_norm/14.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 14,
    "input-text": [
        "When",
        " my",
        " flight",
        " landed",
        " in",
        " Russia",
        ",",
        " I",
        " converted",
        " my",
        " currency",
        " and",
        " slowly",
        " fell",
        " asleep",
        ".",
        " (",
        "I",
        " had",
        " a",
        " terrifying",
        " dream",
        " about",
        " my",
        " grandmother",
        ",",
        " but",
        " that",
        "'s",
        " a",
        " story",
        " for",
        " another",
        " time",
        ").",
        " I",
        " was",
        " staying",
        " in",
        " the",
        " capital",
        ","
    ],
    "input-tokens": [
        2215,
        616,
        5474,
        11406,
        287,
        3284,
        11,
        314,
        11513,
        616,
        7395,
        290,
        6364,
        3214,
        16039,
        13,
        357,
        40,
        550,
        257,
        17623,
        4320,
        546,
        616,
        18410,
        11,
        475,
        326,
        338,
        257,
        1621,
        329,
        1194,
        640,
        737,
        314,
        373,
        10589,
        287,
        262,
        3139,
        11
    ],
    "target-text": " Moscow",
    "target-token": 9070,
    "rational-size": 5,
    "rational-positions": [
        40,
        5,
        37,
        0,
        2
    ],
    "rational-text": [
        " capital",
        " Russia",
        " staying",
        "When",
        " flight"
    ],
    "rational-tokens": [
        3139,
        3284,
        10589,
        2215,
        5474
    ],
    "importance-scores": [
        0.02870972268283367,
        0.024930497631430626,
        0.028489328920841217,
        0.025900879874825478,
        0.02237175777554512,
        0.035737212747335434,
        0.020986400544643402,
        0.021148663014173508,
        0.02437606267631054,
        0.021524690091609955,
        0.02601613849401474,
        0.021364305168390274,
        0.022689446806907654,
        0.021890971809625626,
        0.023894591256976128,
        0.022141598165035248,
        0.02283666282892227,
        0.021497394889593124,
        0.021288538351655006,
        0.020481066778302193,
        0.026239585131406784,
        0.022448519244790077,
        0.02168267033994198,
        0.02163434773683548,
        0.024474158883094788,
        0.020613400265574455,
        0.021757619455456734,
        0.020982077345252037,
        0.022195778787136078,
        0.020805545151233673,
        0.022680891677737236,
        0.02050144597887993,
        0.02145874686539173,
        0.020716534927487373,
        0.025155486539006233,
        0.022285988554358482,
        0.021809959784150124,
        0.029002435505390167,
        0.02161557972431183,
        0.022214481607079506,
        0.04567864537239075,
        0.025770124047994614
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "gpt2-xl",
            "cache_dir": "cache/",
            "tokenizer": "gpt2-xl",
            "data_dir": "data/analogies/gpt2_xl/",
            "importance_results_dir": "rationalization_results/analogies/gpt2_xl_norm",
            "device": "cuda",
            "rationalization_config": "config/eva_norm.json",
            "input_num_ratio": 1,
            "logfolder": "logs/analogies/gpt2_xl_norm",
            "loglevel": 20
        },
        "time_elapsed": 0.06420636177062988
    }
}

=== casszhao/ReAGent/rationalization_results/analogies/gpt2_attention_last/119.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 119,
    "input-text": [
        "I",
        " had",
        " never",
        " been",
        " friends",
        " with",
        " any",
        " Bulgarian",
        " people",
        " before",
        ".",
        " (",
        "The",
        " funn",
        "iest",
        " thing",
        " happened",
        " to",
        " me",
        " the",
        " other",
        " day",
        ",",
        " but",
        " that",
        "'s",
        " a",
        " story",
        " for",
        " another",
        " time",
        ").",
        " In",
        " fact",
        ",",
        " I",
        " had",
        " never",
        " even",
        " been",
        " to"
    ],
    "input-tokens": [
        40,
        550,
        1239,
        587,
        2460,
        351,
        597,
        42119,
        661,
        878,
        13,
        357,
        464,
        36090,
        6386,
        1517,
        3022,
        284,
        502,
        262,
        584,
        1110,
        11,
        475,
        326,
        338,
        257,
        1621,
        329,
        1194,
        640,
        737,
        554,
        1109,
        11,
        314,
        550,
        1239,
        772,
        587,
        284
    ],
    "target-text": " Bulgaria",
    "target-token": 27902,
    "rational-size": 5,
    "rational-positions": [
        0,
        40,
        7,
        32,
        10
    ],
    "rational-text": [
        "I",
        " to",
        " Bulgarian",
        " In",
        "."
    ],
    "rational-tokens": [
        40,
        284,
        42119,
        554,
        13
    ],
    "importance-scores": [
        0.0357280895113945,
        0.024041691794991493,
        0.024016017094254494,
        0.023881400004029274,
        0.023919854313135147,
        0.02421284280717373,
        0.023934204131364822,
        0.02544364146888256,
        0.024163728579878807,
        0.024196257814764977,
        0.024681685492396355,
        0.024426663294434547,
        0.02421465329825878,
        0.02385169453918934,
        0.02385774441063404,
        0.023829232901334763,
        0.02389148250222206,
        0.023921938613057137,
        0.023948723450303078,
        0.02387220412492752,
        0.023836709558963776,
        0.02394598163664341,
        0.024042798206210136,
        0.023868801072239876,
        0.02379039116203785,
        0.023790715262293816,
        0.02379004657268524,
        0.023804398253560066,
        0.023820487782359123,
        0.02378397434949875,
        0.0238186102360487,
        0.02448238991200924,
        0.024874409660696983,
        0.024096837267279625,
        0.02443055622279644,
        0.02406265400350094,
        0.023963408544659615,
        0.023933665826916695,
        0.02391430363059044,
        0.023890309035778046,
        0.026024790480732918
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "gpt2-medium",
            "cache_dir": "./cache/",
            "tokenizer": "gpt2-medium",
            "data_dir": "data/analogies/gpt2/",
            "importance_results_dir": "rationalization_results/analogies/gpt2_attention_last",
            "device": "cuda",
            "rationalization_config": "config/eva_attention_last.json",
            "input_num_ratio": 1,
            "logfolder": "logs/analogies/gpt2_attention_last",
            "loglevel": 20
        },
        "time_elapsed": 0.013032674789428711
    }
}

=== casszhao/ReAGent/rationalization_results/analogies/gpt2_xl_ours/top3_replace0.1_max5000_batch5/157.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 157,
    "input-text": [
        "I",
        " had",
        " never",
        " been",
        " friends",
        " with",
        " any",
        " Israeli",
        " people",
        " before",
        ".",
        " (",
        "The",
        " funn",
        "iest",
        " thing",
        " happened",
        " to",
        " me",
        " the",
        " other",
        " day",
        ",",
        " but",
        " that",
        "'s",
        " a",
        " story",
        " for",
        " another",
        " time",
        ").",
        " In",
        " fact",
        ",",
        " I",
        " had",
        " never",
        " even",
        " been",
        " to"
    ],
    "input-tokens": [
        40,
        550,
        1239,
        587,
        2460,
        351,
        597,
        6085,
        661,
        878,
        13,
        357,
        464,
        36090,
        6386,
        1517,
        3022,
        284,
        502,
        262,
        584,
        1110,
        11,
        475,
        326,
        338,
        257,
        1621,
        329,
        1194,
        640,
        737,
        554,
        1109,
        11,
        314,
        550,
        1239,
        772,
        587,
        284
    ],
    "target-text": " Israel",
    "target-token": 2692,
    "rational-size": 8,
    "rational-positions": [
        7,
        17,
        23,
        25,
        28,
        30,
        39,
        40
    ],
    "rational-text": [
        " Israeli",
        " to",
        " but",
        "'s",
        " for",
        " time",
        " been",
        " to"
    ],
    "rational-tokens": [
        6085,
        284,
        475,
        338,
        329,
        640,
        587,
        284
    ],
    "importance-scores": [
        8.942087958985212e-08,
        3.8766521015531907e-07,
        0.0001983251131605357,
        9.414157830178738e-06,
        5.843485268997028e-07,
        4.278143478586571e-06,
        5.547113687498495e-05,
        0.38219815492630005,
        1.4878725096423295e-07,
        0.0003216892364434898,
        8.202487578046203e-08,
        2.9004189627812593e-07,
        2.9077631324980757e-07,
        3.5739583381655393e-06,
        0.0011244128691032529,
        2.1431478103295376e-07,
        6.699382311126101e-07,
        5.243018108558317e-07,
        1.7741398323778412e-06,
        4.6519065932670856e-08,
        9.157535174608711e-08,
        8.233807307078678e-07,
        1.5935572719172342e-06,
        4.797144720214419e-05,
        4.0143464730135747e-07,
        5.556897804126493e-07,
        3.842397745756898e-06,
        0.001244959537871182,
        0.1033368930220604,
        0.012726493179798126,
        0.02858864702284336,
        8.224229532061145e-06,
        2.939001660706708e-06,
        0.008928603492677212,
        2.2223828636924736e-05,
        0.0003031688102055341,
        2.181147920055082e-07,
        0.005693280138075352,
        0.004906428512185812,
        0.4502001404762268,
        6.212273729033768e-05
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "gpt2-xl",
            "cache_dir": "cache/",
            "tokenizer": "gpt2-xl",
            "data_dir": "data/analogies/gpt2_xl",
            "importance_results_dir": "rationalization_results/analogies/gpt2_xl_ours/top3_replace0.1_max5000_batch5",
            "device": "cuda",
            "rationalization_config": "config//top3_replace0.1_max5000_batch5.json",
            "input_num_ratio": 1.0,
            "logfolder": "logs/analogies/gpt2_xl_ours/top3_replace0.1_max5000_batch5",
            "loglevel": 20
        },
        "time_elapsed": 24.180296182632446,
        "separate_rational": [
            [
                " Israeli",
                " been",
                " to",
                "'s",
                " had",
                " any",
                " the",
                " ("
            ],
            [
                " Israeli",
                " been",
                " time",
                " never",
                " never",
                " for",
                " to",
                " but"
            ],
            [
                " been",
                " to",
                "'s",
                " Israeli",
                " had",
                " time",
                " me",
                " people"
            ],
            [
                " for",
                " Israeli",
                " another",
                " fact",
                " even",
                " story",
                " been",
                "iest"
            ],
            [
                " been",
                " Israeli",
                " but",
                " to",
                " friends",
                " thing",
                ").",
                " time"
            ]
        ]
    }
}

=== casszhao/ReAGent/rationalization_results/analogies/gpt2_ours/top3_replace0.3_max3000_batch3/9.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 9,
    "input-text": [
        "When",
        " my",
        " flight",
        " landed",
        " in",
        " Pakistan",
        ",",
        " I",
        " converted",
        " my",
        " currency",
        " and",
        " slowly",
        " fell",
        " asleep",
        ".",
        " (",
        "I",
        " had",
        " a",
        " terrifying",
        " dream",
        " about",
        " my",
        " grandmother",
        ",",
        " but",
        " that",
        "'s",
        " a",
        " story",
        " for",
        " another",
        " time",
        ").",
        " I",
        " was",
        " staying",
        " in",
        " the",
        " capital",
        ","
    ],
    "input-tokens": [
        2215,
        616,
        5474,
        11406,
        287,
        7648,
        11,
        314,
        11513,
        616,
        7395,
        290,
        6364,
        3214,
        16039,
        13,
        357,
        40,
        550,
        257,
        17623,
        4320,
        546,
        616,
        18410,
        11,
        475,
        326,
        338,
        257,
        1621,
        329,
        1194,
        640,
        737,
        314,
        373,
        10589,
        287,
        262,
        3139,
        11
    ],
    "target-text": " Islamabad",
    "target-token": 36878,
    "rational-size": 2,
    "rational-positions": [
        5,
        26
    ],
    "rational-text": [
        " Pakistan",
        " but"
    ],
    "rational-tokens": [
        7648,
        475
    ],
    "importance-scores": [
        9.486672114409809e-23,
        4.83795338368509e-06,
        3.403950824253249e-36,
        8.91232266967457e-28,
        0.9999948740005493,
        1.6313250750243924e-10,
        6.178347056368247e-31,
        7.949830595737986e-20,
        2.489703835558297e-18,
        3.218051808373274e-15,
        3.4252387801387447e-34,
        2.6578768140853617e-35,
        5.105920746118714e-29,
        2.9274439842821718e-30,
        7.117870377393812e-27,
        3.4287501193830394e-07,
        7.547724154030981e-31,
        2.303627483236968e-33,
        5.54943427144156e-19,
        6.990459412715595e-19,
        1.0647254375590548e-21,
        5.911653954338999e-32,
        3.984277587286805e-25,
        4.255206241469524e-27,
        1.8293703421932301e-38,
        4.937023245106519e-22,
        1.4158167378115618e-26,
        4.239336926935907e-23,
        2.733746104499204e-19,
        6.2851046414263e-16,
        1.9250097584497307e-18,
        3.2310152593227055e-31,
        2.4813486768776594e-12,
        1.9539057815726678e-20,
        2.3887759767841873e-27,
        3.9485611322087086e-29,
        1.9628479860343036e-35,
        6.627994334258347e-31,
        8.928030078338969e-16,
        3.7159316422508137e-13,
        2.788593578273435e-09,
        4.403810345977087e-30
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "gpt2-medium",
            "cache_dir": "cache/",
            "tokenizer": "gpt2-medium",
            "data_dir": "data/analogies/gpt2/",
            "importance_results_dir": "rationalization_results/analogies/gpt2_ours/top3_replace0.3_max3000_batch3",
            "device": "cuda",
            "rationalization_config": "config/gpt2/top3_replace0.3_max3000_batch3.json",
            "input_num_ratio": 1.0,
            "logfolder": "logs/analogies/gpt2_ours/top3_replace0.3_max3000_batch3",
            "loglevel": 20
        },
        "time_elapsed": 111.9455394744873,
        "separate_rational": [
            [
                " in",
                " my",
                ".",
                " capital",
                " Pakistan",
                " another",
                " the",
                " my"
            ],
            [
                " Pakistan",
                " (",
                ").",
                " but",
                " slowly",
                " that",
                " for",
                " was"
            ],
            [
                " staying",
                " flight",
                " I",
                " but",
                ",",
                " currency",
                "When",
                " time"
            ]
        ]
    }
}

=== casszhao/ReAGent/rationalization_results/analogies/gpt2_attention/45.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 45,
    "input-text": [
        "When",
        " my",
        " flight",
        " landed",
        " in",
        " Philippines",
        ",",
        " I",
        " converted",
        " my",
        " currency",
        " and",
        " slowly",
        " fell",
        " asleep",
        ".",
        " (",
        "I",
        " was",
        " behind",
        " on",
        " a",
        " couple",
        " of",
        " assignments",
        ",",
        " but",
        " I",
        " tried",
        " not",
        " to",
        " think",
        " about",
        " them",
        ").",
        " I",
        " was",
        " staying",
        " in",
        " the",
        " capital",
        ","
    ],
    "input-tokens": [
        2215,
        616,
        5474,
        11406,
        287,
        13316,
        11,
        314,
        11513,
        616,
        7395,
        290,
        6364,
        3214,
        16039,
        13,
        357,
        40,
        373,
        2157,
        319,
        257,
        3155,
        286,
        25815,
        11,
        475,
        314,
        3088,
        407,
        284,
        892,
        546,
        606,
        737,
        314,
        373,
        10589,
        287,
        262,
        3139,
        11
    ],
    "target-text": " Manila",
    "target-token": 31721,
    "rational-size": 5,
    "rational-positions": [
        0,
        40,
        41,
        5,
        37
    ],
    "rational-text": [
        "When",
        " capital",
        ",",
        " Philippines",
        " staying"
    ],
    "rational-tokens": [
        2215,
        3139,
        11,
        13316,
        10589
    ],
    "importance-scores": [
        0.03802988678216934,
        0.02331063523888588,
        0.023297179490327835,
        0.02331448718905449,
        0.02338058315217495,
        0.024253366515040398,
        0.023396892473101616,
        0.023335633799433708,
        0.02327989600598812,
        0.023263132199645042,
        0.023277591913938522,
        0.023294972255825996,
        0.023259464651346207,
        0.023254211992025375,
        0.023293856531381607,
        0.023482825607061386,
        0.023323625326156616,
        0.02326291613280773,
        0.023268088698387146,
        0.02326340787112713,
        0.023248033598065376,
        0.023248689249157906,
        0.023235855624079704,
        0.023224979639053345,
        0.02330034039914608,
        0.023306410759687424,
        0.02331107296049595,
        0.023257749155163765,
        0.02326262928545475,
        0.023250380530953407,
        0.02325562760233879,
        0.023256119340658188,
        0.02327689714729786,
        0.023267829790711403,
        0.023775359615683556,
        0.02362356148660183,
        0.023734750226140022,
        0.023936618119478226,
        0.023886455222964287,
        0.023790080100297928,
        0.025265367701649666,
        0.02444254234433174
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "gpt2-medium",
            "cache_dir": "./cache/",
            "tokenizer": "gpt2-medium",
            "data_dir": "data/analogies/gpt2/",
            "importance_results_dir": "rationalization_results/analogies/gpt2_attention",
            "device": "cuda",
            "rationalization_config": "config/eva_attention.json",
            "input_num_ratio": 1,
            "logfolder": "logs/analogies/gpt2_attention",
            "loglevel": 20
        },
        "time_elapsed": 0.013713598251342773
    }
}

=== casszhao/ReAGent/rationalization_results/analogies/gpt2_ours/backup/top5_replace0.3_max3000/107.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 107,
    "input-text": [
        "I",
        " thought",
        " it",
        " would",
        " be",
        " the",
        " oldest",
        " thing",
        " I",
        "'d",
        " ever",
        " encounter",
        ".",
        " (",
        "I",
        " tried",
        " to",
        " ignore",
        " my",
        " phone",
        " vibr",
        "ating",
        " in",
        " my",
        " pocket",
        ").",
        " But",
        " when",
        " I",
        " did",
        " end",
        " up",
        " encountering",
        " it",
        ",",
        " it",
        " turned",
        " out",
        " it",
        " wasn",
        "'t",
        " so"
    ],
    "input-tokens": [
        40,
        1807,
        340,
        561,
        307,
        262,
        13325,
        1517,
        314,
        1549,
        1683,
        8791,
        13,
        357,
        40,
        3088,
        284,
        8856,
        616,
        3072,
        12611,
        803,
        287,
        616,
        10000,
        737,
        887,
        618,
        314,
        750,
        886,
        510,
        42398,
        340,
        11,
        340,
        2900,
        503,
        340,
        2492,
        470,
        523
    ],
    "target-text": " old",
    "target-token": 1468,
    "rational-size": 4,
    "rational-positions": [
        0,
        6,
        40,
        41
    ],
    "rational-text": [
        "I",
        " oldest",
        "'t",
        " so"
    ],
    "rational-tokens": [
        40,
        13325,
        470,
        523
    ],
    "importance-scores": [
        3.056338300666539e-06,
        1.2378422632525776e-21,
        3.6129633569182356e-21,
        1.3598597433883697e-05,
        2.523740663403629e-18,
        4.724327765806895e-21,
        0.20000000298023224,
        0.20000000298023224,
        1.2893261272216791e-26,
        6.550975853360924e-14,
        1.6626060320563919e-15,
        2.5629347135678104e-21,
        5.225370756837426e-19,
        1.228746509266484e-24,
        3.9469912527147905e-14,
        6.736789132186921e-14,
        6.844833023933461e-06,
        4.4101223693770826e-17,
        0.17553463578224182,
        0.1927809864282608,
        8.50051407041974e-08,
        1.3817588911555298e-17,
        3.21949511494779e-09,
        1.9205312016412539e-28,
        8.443581036472453e-19,
        2.1315917509822507e-13,
        0.1999906599521637,
        1.0765749448265113e-24,
        2.154561643017615e-22,
        5.656583130011536e-24,
        1.4760359081161995e-15,
        2.9226819112245583e-19,
        0.024462301284074783,
        2.5071851723623695e-06,
        4.466302748549686e-22,
        6.014312041013187e-14,
        7.705638292157188e-15,
        1.0408782001621275e-20,
        2.461112657492768e-25,
        4.671252828991612e-10,
        1.3668082219690932e-18,
        0.007205330766737461
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "gpt2-medium",
            "cache_dir": "cache/",
            "tokenizer": "gpt2-medium",
            "data_dir": "data/analogies/gpt2/",
            "importance_results_dir": "rationalization_results/analogies/gpt2_ours",
            "device": "cuda",
            "rationalization_config": "config/aggregation.replacing_delta_prob.postag.json",
            "input_num_ratio": 1.0,
            "logfolder": "logs/analogies/gpt2_ours",
            "loglevel": 20
        },
        "time_elapsed": 108.0810956954956,
        "separate_rational": [
            [
                " thing",
                "'t",
                " thought",
                " so",
                ","
            ],
            [
                " But",
                " to",
                " it",
                " wasn",
                " so"
            ],
            [
                " phone",
                " so",
                " would",
                " vibr",
                " in"
            ],
            [
                " my",
                " encountering",
                "I",
                " oldest",
                ")."
            ],
            [
                " oldest",
                "'t",
                " it",
                " turned",
                "I"
            ]
        ]
    }
}
