=== casszhao/ReAGent/docs/rationalization.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Rational results",
    "description": "Rational results from experiments",
    "type": "object",
    "properties": {
        "id": {
            "type": "number",
            "minimum": -1
        },
        "input-text": {
            "description": "Text corresponding to input-tokens",
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "input-tokens": {
            "description": "Tokens of the input sequence",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 0
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "target-text": {
            "description": "Text corresponding to target-token",
            "type": "string"
        },
        "target-token": {
            "description": "Target token to predict from the input sequence",
            "type": "number",
            "minimum": 0
        },
        "importance-scores": {
            "description": "Importance scores of each token in the input sequence",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "rational-size": {
            "description": "Size of the rational. Define how many items in the rational-tokens.",
            "type": "number",
            "minimum": 1
        },
        "rational-positions": {
            "description": "Positions of tokens of input which included in the rational",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 0
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "rational-text": {
            "description": "Text corresponding to rational-tokens",
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "rational-tokens": {
            "description": "Tokens included in the rational",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 0
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "comments": {
            "description": "Additional comments",
            "type": "object"
        },
        "trace": {
            "description": "Trace of the process",
            "type": "object",
            "properties": {
                "importance-scores": {
                    "description": "Trace of importance scores",
                    "type": "array",
                    "items": {
                        "description": "One stage of importance scores",
                        "type": "array",
                        "items": {
                            "type": "number",
                            "minimum": 0,
                            "maximum": 1
                        },
                        "minItems": 1,
                        "uniqueItems": false
                    }
                },
                "target-likelihood-original": {
                    "description": "Target likelihood with the original sequence",
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                },
                "target-likelihood": {
                    "description": "Trace of target likelihood with rational not replaced",
                    "type": "array",
                    "items": {
                        "description": "One stage of target likelihood with rational not replaced",
                        "type": "number",
                        "minimum": 0,
                        "maximum": 1
                    }
                }
            },
            "required": [
                "importance-scores",
                "target-likelihood-original",
                "target-likelihood"
            ]
        }
    },
    "required": [
        "input-text",
        "input-tokens",
        "target-text",
        "target-token",
        "rational-size",
        "rational-positions",
        "rational-text",
        "rational-tokens"
    ]
}

=== casszhao/ReAGent/rationalization_results/analogies/gpt2_ours/top3_replace0.1_max3000_batch5/40.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 40,
    "input-text": [
        "When",
        " my",
        " flight",
        " landed",
        " in",
        " Jamaica",
        ",",
        " I",
        " converted",
        " my",
        " currency",
        " and",
        " slowly",
        " fell",
        " asleep",
        ".",
        " (",
        "I",
        " was",
        " behind",
        " on",
        " a",
        " couple",
        " of",
        " assignments",
        ",",
        " but",
        " I",
        " tried",
        " not",
        " to",
        " think",
        " about",
        " them",
        ").",
        " I",
        " was",
        " staying",
        " in",
        " the",
        " capital",
        ","
    ],
    "input-tokens": [
        2215,
        616,
        5474,
        11406,
        287,
        31620,
        11,
        314,
        11513,
        616,
        7395,
        290,
        6364,
        3214,
        16039,
        13,
        357,
        40,
        373,
        2157,
        319,
        257,
        3155,
        286,
        25815,
        11,
        475,
        314,
        3088,
        407,
        284,
        892,
        546,
        606,
        737,
        314,
        373,
        10589,
        287,
        262,
        3139,
        11
    ],
    "target-text": " Kingston",
    "target-token": 34612,
    "rational-size": 10,
    "rational-positions": [
        3,
        4,
        5,
        34,
        35,
        36,
        37,
        38,
        39,
        40
    ],
    "rational-text": [
        " landed",
        " in",
        " Jamaica",
        ").",
        " I",
        " was",
        " staying",
        " in",
        " the",
        " capital"
    ],
    "rational-tokens": [
        11406,
        287,
        31620,
        737,
        314,
        373,
        10589,
        287,
        262,
        3139
    ],
    "importance-scores": [
        9.37985533567652e-34,
        2.4597534237262318e-21,
        1.3727954756425428e-33,
        3.1885903639672364e-11,
        0.1963234841823578,
        0.20000000298023224,
        1.0252585320739188e-32,
        8.086155259812524e-19,
        8.106645507144141e-28,
        3.161012454841407e-32,
        2.3323712665029183e-26,
        3.628648284607632e-21,
        5.290761601653084e-22,
        2.748122071746582e-26,
        6.563389588765123e-12,
        1.0836746929735004e-24,
        6.061621205775079e-37,
        8.235897808513665e-32,
        1.8945555237671527e-42,
        2.717390094226131e-21,
        1.4309170782073774e-28,
        6.63116741319617e-18,
        1.6228229863091991e-34,
        7.3697592051926645e-22,
        3.740639609150658e-32,
        1.7312863967443943e-21,
        6.803609005862669e-22,
        1.3792254247228852e-25,
        2.2257320632590104e-26,
        3.4453638986118625e-19,
        1.9230324213045041e-26,
        2.1893206332502708e-35,
        6.638971336805892e-23,
        1.5404645015341141e-24,
        0.20365948975086212,
        7.691095760264943e-08,
        1.403771292221199e-16,
        2.960721945388656e-11,
        4.08793130191043e-06,
        0.20001240074634552,
        0.20000047981739044,
        1.300247385914735e-20
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "gpt2-medium",
            "cache_dir": "cache/",
            "tokenizer": "gpt2-medium",
            "data_dir": "data/analogies/gpt2/",
            "importance_results_dir": "rationalization_results/analogies/gpt2_ours/top3_replace0.1_max3000_batch5",
            "device": "cuda",
            "rationalization_config": "config/gpt2/top3_replace0.1_max3000_batch5.json",
            "input_num_ratio": 1.0,
            "logfolder": "logs/analogies/gpt2_ours/top3_replace0.1_max3000_batch5",
            "loglevel": 20
        },
        "time_elapsed": 59.00793242454529,
        "separate_rational": [
            [
                ").",
                " I",
                " Jamaica",
                " landed",
                " the",
                " asleep",
                " capital",
                " a"
            ],
            [
                " the",
                " capital",
                " I",
                " Jamaica",
                ").",
                " I",
                " in",
                " in"
            ],
            [
                " in",
                ").",
                " the",
                " in",
                " capital",
                " staying",
                " Jamaica",
                " landed"
            ],
            [
                " capital",
                " Jamaica",
                " the",
                " was",
                " in",
                ").",
                " about",
                ","
            ],
            [
                " Jamaica",
                ").",
                " staying",
                " landed",
                " the",
                " was",
                " in",
                " capital"
            ]
        ]
    }
}

=== casszhao/ReAGent/rationalization_results/analogies/OPT1B_ours/top3_replace0.3_max3000_batch10/7.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 7,
    "input-text": [
        "</s>",
        "As",
        " soon",
        " as",
        " I",
        " arrived",
        " in",
        " Iran",
        ",",
        " I",
        " checked",
        " into",
        " my",
        " hotel",
        " and",
        " took",
        " a",
        " long",
        " nap",
        ".",
        " (",
        "I",
        " had",
        " finally",
        " finished",
        " the",
        " book",
        " I",
        " was",
        " reading",
        " and",
        " it",
        " was",
        " amazing",
        ").",
        " I",
        " had",
        " to",
        " figure",
        " out",
        " the",
        " exchange",
        " rate",
        " to",
        " the",
        " local",
        " currency",
        ",",
        " which",
        " is",
        " apparently",
        " called",
        " the",
        " r"
    ],
    "input-tokens": [
        2,
        1620,
        1010,
        25,
        38,
        2035,
        11,
        1603,
        6,
        38,
        7869,
        88,
        127,
        2303,
        8,
        362,
        10,
        251,
        16159,
        4,
        36,
        100,
        56,
        1747,
        1550,
        5,
        1040,
        38,
        21,
        2600,
        8,
        24,
        21,
        2770,
        322,
        38,
        56,
        7,
        1955,
        66,
        5,
        2081,
        731,
        7,
        5,
        400,
        2593,
        6,
        61,
        16,
        4100,
        373,
        5,
        910
    ],
    "target-text": "ial",
    "target-token": 2617,
    "rational-size": 9,
    "rational-positions": [
        0,
        1,
        2,
        3,
        7,
        29,
        45,
        46,
        53
    ],
    "rational-text": [
        "</s>",
        "As",
        " soon",
        " as",
        " Iran",
        " reading",
        " local",
        " currency",
        " r"
    ],
    "rational-tokens": [
        2,
        1620,
        1010,
        25,
        1603,
        2600,
        400,
        2593,
        910
    ],
    "importance-scores": [
        0.014088108204305172,
        2.6452244838992556e-09,
        0.003929419908672571,
        9.349735612465548e-13,
        2.048704095258813e-09,
        0.0508643239736557,
        9.879678455546048e-13,
        0.34868332743644714,
        2.928800979518087e-09,
        6.9520980083837e-09,
        1.1789316886279266e-05,
        3.163966539432295e-05,
        1.4521061020289494e-09,
        2.2782304931467934e-09,
        1.1846099188389525e-12,
        9.46460113482317e-06,
        0.005051278974860907,
        1.1794605006207326e-12,
        3.0532310620751124e-12,
        1.6079242971811514e-12,
        5.384238832562005e-09,
        2.4126800817619865e-12,
        5.413442139001745e-09,
        1.653824188707631e-09,
        3.500132475520168e-12,
        1.6718995077269483e-09,
        1.3200943159777379e-12,
        2.1673416100015386e-12,
        1.5406637077219898e-09,
        0.07708416879177094,
        1.495950073149288e-06,
        1.1383028851105759e-12,
        6.612464482219638e-13,
        1.274301109077669e-09,
        3.5739085433306172e-06,
        1.0260374364370883e-12,
        1.4521123858912688e-08,
        5.169446648523035e-09,
        1.1993142834398896e-05,
        5.9498492191778496e-05,
        4.139441898587393e-06,
        2.890849145842367e-06,
        6.66954136363529e-09,
        4.821878974325955e-05,
        5.945912207039328e-09,
        8.72203020918505e-09,
        2.440576827211771e-05,
        1.110247202333603e-12,
        8.282216003863141e-05,
        6.558403451394079e-13,
        1.5093784000441701e-09,
        7.371383617282845e-06,
        9.478456908240673e-10,
        0.5
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "facebook/opt-1.3b",
            "cache_dir": "cache/",
            "tokenizer": "facebook/opt-1.3b",
            "data_dir": "data/analogies/OPT1B",
            "importance_results_dir": "rationalization_results/analogies/OPT1B_ours/top3_replace0.3_max3000_batch10",
            "device": "cuda",
            "rationalization_config": "config//top3_replace0.3_max3000_batch10.json",
            "input_num_ratio": 1.0,
            "logfolder": "logs/analogies/OPT1B_ours/top3_replace0.3_max3000_batch10",
            "loglevel": 20
        },
        "time_elapsed": 750.8062453269958,
        "separate_rational": [
            [
                " r",
                " which",
                " rate",
                " the",
                "As"
            ],
            [
                " Iran",
                " local",
                " r",
                " currency",
                " reading"
            ],
            [
                " r",
                "</s>",
                "As",
                " soon",
                " as"
            ],
            [
                " r",
                "</s>",
                "As",
                " soon",
                " as"
            ],
            [
                " Iran",
                " called",
                " currency",
                " r",
                " is"
            ],
            [
                " r",
                "</s>",
                "As",
                " soon",
                " as"
            ],
            [
                " r",
                "</s>",
                "As",
                " soon",
                " as"
            ],
            [
                " r",
                "</s>",
                "As",
                " soon",
                " as"
            ],
            [
                " reading",
                " arrived",
                " Iran",
                "</s>",
                " a"
            ],
            [
                " r",
                " into",
                " currency",
                " Iran",
                " local"
            ]
        ]
    }
}

=== casszhao/ReAGent/rationalization_results/analogies/gpt2_xl_input_x_gradient/82.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 82,
    "input-text": [
        "I",
        " initially",
        " invited",
        " my",
        " father",
        ",",
        " who",
        " gladly",
        " accepted",
        " my",
        " invitation",
        ".",
        " (",
        "My",
        " favorite",
        " song",
        " just",
        " came",
        " on",
        ",",
        " so",
        " I",
        " was",
        " able",
        " to",
        " relax",
        ").",
        " When",
        " I",
        " learned",
        " that",
        " women",
        " were",
        " allowed",
        ",",
        " I",
        " went",
        " ahead",
        " and",
        " also",
        " invited",
        " my"
    ],
    "input-tokens": [
        40,
        7317,
        9392,
        616,
        2988,
        11,
        508,
        35092,
        6292,
        616,
        17023,
        13,
        357,
        3666,
        4004,
        3496,
        655,
        1625,
        319,
        11,
        523,
        314,
        373,
        1498,
        284,
        8960,
        737,
        1649,
        314,
        4499,
        326,
        1466,
        547,
        3142,
        11,
        314,
        1816,
        4058,
        290,
        635,
        9392,
        616
    ],
    "target-text": " mother",
    "target-token": 2802,
    "rational-size": 5,
    "rational-positions": [
        4,
        7,
        31,
        1,
        2
    ],
    "rational-text": [
        " father",
        " gladly",
        " women",
        " initially",
        " invited"
    ],
    "rational-tokens": [
        2988,
        35092,
        1466,
        7317,
        9392
    ],
    "importance-scores": [
        0.043117742985486984,
        0.06215185672044754,
        0.06036146357655525,
        0.03035087138414383,
        0.12936046719551086,
        0.007074658293277025,
        0.009689857251942158,
        0.06893184781074524,
        0.026047084480524063,
        0.01084339339286089,
        0.04301472753286362,
        0.007526481989771128,
        0.010639735497534275,
        0.011742641218006611,
        0.034725744277238846,
        0.03131844475865364,
        0.008306865580379963,
        0.008119466714560986,
        0.003855816787108779,
        0.002810360863804817,
        0.005413373466581106,
        0.004538011737167835,
        0.004375826101750135,
        0.018761582672595978,
        0.002511802362278104,
        0.039462462067604065,
        0.020639726892113686,
        0.013316269032657146,
        0.0074378978461027145,
        0.033719923347234726,
        0.007822906598448753,
        0.06400185823440552,
        0.006599596701562405,
        0.027964763343334198,
        0.005534464027732611,
        0.00991879403591156,
        0.011562522500753403,
        0.021173590794205666,
        0.004925164394080639,
        0.019001487642526627,
        0.04284331575036049,
        0.01848502643406391
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "gpt2-xl",
            "cache_dir": "./cache/",
            "tokenizer": "gpt2-xl",
            "data_dir": "data/analogies/gpt2_xl/",
            "importance_results_dir": "rationalization_results/analogies/gpt2_xl_input_x_gradient",
            "device": "cuda",
            "rationalization_config": "config/eva_input_x_gradient.json",
            "input_num_ratio": 1,
            "logfolder": "logs/analogies/gpt2_xl_input_x_gradient",
            "loglevel": 20
        },
        "time_elapsed": 0.13541698455810547
    }
}

=== casszhao/ReAGent/rationalization_results/analogies/OPT6B_last_attention/20.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 20,
    "input-text": [
        "</s>",
        "I",
        " had",
        " never",
        " been",
        " friends",
        " with",
        " any",
        " Chinese",
        " people",
        " before",
        ".",
        " (",
        "The",
        " funn",
        "iest",
        " thing",
        " happened",
        " to",
        " me",
        " the",
        " other",
        " day",
        ",",
        " but",
        " that",
        "'s",
        " a",
        " story",
        " for",
        " another",
        " time",
        ").",
        " In",
        " fact",
        ",",
        " I",
        " had",
        " never",
        " even",
        " been",
        " to"
    ],
    "input-tokens": [
        2,
        100,
        56,
        393,
        57,
        964,
        19,
        143,
        1111,
        82,
        137,
        4,
        36,
        133,
        29310,
        7098,
        631,
        1102,
        7,
        162,
        5,
        97,
        183,
        6,
        53,
        14,
        18,
        10,
        527,
        13,
        277,
        86,
        322,
        96,
        754,
        6,
        38,
        56,
        393,
        190,
        57,
        7
    ],
    "target-text": " China",
    "target-token": 436,
    "rational-size": 5,
    "rational-positions": [
        0,
        41,
        8,
        32,
        7
    ],
    "rational-text": [
        "</s>",
        " to",
        " Chinese",
        ").",
        " any"
    ],
    "rational-tokens": [
        2,
        7,
        1111,
        322,
        143
    ],
    "importance-scores": [
        0.05685969442129135,
        0.023067086935043335,
        0.023020397871732712,
        0.022999458014965057,
        0.0229802243411541,
        0.022981468588113785,
        0.02298431657254696,
        0.02307029813528061,
        0.023251090198755264,
        0.023005113005638123,
        0.0229951124638319,
        0.02302982285618782,
        0.0229850634932518,
        0.02305559627711773,
        0.022960897535085678,
        0.022974874824285507,
        0.02297215908765793,
        0.022981001064181328,
        0.022972971200942993,
        0.02300241030752659,
        0.022968197241425514,
        0.022967642173171043,
        0.02297491393983364,
        0.022971976548433304,
        0.022961856797337532,
        0.022956103086471558,
        0.022954972460865974,
        0.022954529151320457,
        0.022955527529120445,
        0.022954454645514488,
        0.02295507676899433,
        0.022955693304538727,
        0.023100895807147026,
        0.02301962487399578,
        0.023004528135061264,
        0.02299323119223118,
        0.022995078936219215,
        0.02296929992735386,
        0.022991839796304703,
        0.02299955114722252,
        0.022988203912973404,
        0.023257622495293617
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "KoboldAI/OPT-6.7B-Erebus",
            "cache_dir": "cache/",
            "tokenizer": "KoboldAI/OPT-6.7B-Erebus",
            "data_dir": "data/analogies/OPT6B/",
            "importance_results_dir": "rationalization_results/analogies/OPT6B_last_attention",
            "device": "cuda",
            "rationalization_config": "config/eva_last_attention.json",
            "input_num_ratio": 1,
            "logfolder": "logs/analogies/OPT6B_last_attention",
            "loglevel": 20
        },
        "time_elapsed": 0.07737278938293457
    }
}

=== casszhao/ReAGent/rationalization_results/analogies/gpt2_attention_rollout/7.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 7,
    "input-text": [
        "When",
        " my",
        " flight",
        " landed",
        " in",
        " Cuba",
        ",",
        " I",
        " converted",
        " my",
        " currency",
        " and",
        " slowly",
        " fell",
        " asleep",
        ".",
        " (",
        "I",
        " had",
        " a",
        " terrifying",
        " dream",
        " about",
        " my",
        " grandmother",
        ",",
        " but",
        " that",
        "'s",
        " a",
        " story",
        " for",
        " another",
        " time",
        ").",
        " I",
        " was",
        " staying",
        " in",
        " the",
        " capital",
        ","
    ],
    "input-tokens": [
        2215,
        616,
        5474,
        11406,
        287,
        14159,
        11,
        314,
        11513,
        616,
        7395,
        290,
        6364,
        3214,
        16039,
        13,
        357,
        40,
        550,
        257,
        17623,
        4320,
        546,
        616,
        18410,
        11,
        475,
        326,
        338,
        257,
        1621,
        329,
        1194,
        640,
        737,
        314,
        373,
        10589,
        287,
        262,
        3139,
        11
    ],
    "target-text": " Havana",
    "target-token": 40274,
    "rational-size": 5,
    "rational-positions": [
        0,
        1,
        2,
        4,
        3
    ],
    "rational-text": [
        "When",
        " my",
        " flight",
        " in",
        " landed"
    ],
    "rational-tokens": [
        2215,
        616,
        5474,
        287,
        11406
    ],
    "importance-scores": [
        0.06217160075902939,
        0.02287413366138935,
        0.022874020040035248,
        0.02287396602332592,
        0.02287399210035801,
        0.02287391945719719,
        0.022873954847455025,
        0.02287389524281025,
        0.022873884066939354,
        0.02287386916577816,
        0.02287386730313301,
        0.022873882204294205,
        0.022873852401971817,
        0.022873852401971817,
        0.022873852401971817,
        0.022873880341649055,
        0.022873854264616966,
        0.022873839363455772,
        0.022873837500810623,
        0.022873833775520325,
        0.022873831912875175,
        0.022873828187584877,
        0.022873831912875175,
        0.022873826324939728,
        0.022873828187584877,
        0.022873831912875175,
        0.022873828187584877,
        0.022873828187584877,
        0.022873826324939728,
        0.02287382446229458,
        0.022873826324939728,
        0.022873826324939728,
        0.02287382446229458,
        0.02287382259964943,
        0.022873856127262115,
        0.022873831912875175,
        0.022873830050230026,
        0.022873828187584877,
        0.02287382259964943,
        0.02287382073700428,
        0.02287381887435913,
        0.022873815149068832
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "gpt2-medium",
            "cache_dir": "./cache/",
            "tokenizer": "gpt2-medium",
            "data_dir": "data/analogies/gpt2/",
            "importance_results_dir": "rationalization_results/analogies/gpt2_attention_rollout",
            "device": "cuda",
            "rationalization_config": "config/eva_attention_rollout.json",
            "input_num_ratio": 1,
            "logfolder": "logs/analogies/gpt2_attention_rollout",
            "loglevel": 20
        },
        "time_elapsed": 0.014159679412841797
    }
}
