=== casszhao/ReAGent/docs/rationalization.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Rational results",
    "description": "Rational results from experiments",
    "type": "object",
    "properties": {
        "id": {
            "type": "number",
            "minimum": -1
        },
        "input-text": {
            "description": "Text corresponding to input-tokens",
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "input-tokens": {
            "description": "Tokens of the input sequence",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 0
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "target-text": {
            "description": "Text corresponding to target-token",
            "type": "string"
        },
        "target-token": {
            "description": "Target token to predict from the input sequence",
            "type": "number",
            "minimum": 0
        },
        "importance-scores": {
            "description": "Importance scores of each token in the input sequence",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "rational-size": {
            "description": "Size of the rational. Define how many items in the rational-tokens.",
            "type": "number",
            "minimum": 1
        },
        "rational-positions": {
            "description": "Positions of tokens of input which included in the rational",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 0
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "rational-text": {
            "description": "Text corresponding to rational-tokens",
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "rational-tokens": {
            "description": "Tokens included in the rational",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 0
            },
            "minItems": 1,
            "uniqueItems": false
        },
        "comments": {
            "description": "Additional comments",
            "type": "object"
        },
        "trace": {
            "description": "Trace of the process",
            "type": "object",
            "properties": {
                "importance-scores": {
                    "description": "Trace of importance scores",
                    "type": "array",
                    "items": {
                        "description": "One stage of importance scores",
                        "type": "array",
                        "items": {
                            "type": "number",
                            "minimum": 0,
                            "maximum": 1
                        },
                        "minItems": 1,
                        "uniqueItems": false
                    }
                },
                "target-likelihood-original": {
                    "description": "Target likelihood with the original sequence",
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                },
                "target-likelihood": {
                    "description": "Trace of target likelihood with rational not replaced",
                    "type": "array",
                    "items": {
                        "description": "One stage of target likelihood with rational not replaced",
                        "type": "number",
                        "minimum": 0,
                        "maximum": 1
                    }
                }
            },
            "required": [
                "importance-scores",
                "target-likelihood-original",
                "target-likelihood"
            ]
        }
    },
    "required": [
        "input-text",
        "input-tokens",
        "target-text",
        "target-token",
        "rational-size",
        "rational-positions",
        "rational-text",
        "rational-tokens"
    ]
}

=== casszhao/ReAGent/rationalization_results/analogies/OPT6B_ours/top3_replace0.3_max3000_batch5/32.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 32,
    "input-text": [
        "</s>",
        "Although",
        " I",
        " wrote",
        " yesterday",
        ",",
        " I",
        " had",
        " a",
        " million",
        " things",
        " to",
        " do",
        " today",
        ".",
        " (",
        "I",
        " suddenly",
        " felt",
        " a",
        " pin",
        "ched",
        " nerve",
        ",",
        " so",
        " I",
        " made",
        " a",
        " mental",
        " note",
        " to",
        " get",
        " that",
        " checked",
        " out",
        ").",
        " So",
        " today",
        " I",
        " wouldn",
        "'t",
        " have",
        " time",
        " to",
        " do",
        " any",
        " more"
    ],
    "input-tokens": [
        2,
        13863,
        38,
        875,
        2350,
        6,
        38,
        56,
        10,
        153,
        383,
        7,
        109,
        452,
        4,
        36,
        100,
        6017,
        1299,
        10,
        7756,
        3804,
        10387,
        6,
        98,
        38,
        156,
        10,
        2536,
        1591,
        7,
        120,
        14,
        7869,
        66,
        322,
        407,
        452,
        38,
        1979,
        75,
        33,
        86,
        7,
        109,
        143,
        55
    ],
    "target-text": " writing",
    "target-token": 2410,
    "rational-size": 10,
    "rational-positions": [
        3,
        8,
        9,
        22,
        26,
        29,
        32,
        41,
        44,
        46
    ],
    "rational-text": [
        " wrote",
        " a",
        " million",
        " nerve",
        " made",
        " note",
        " that",
        " have",
        " do",
        " more"
    ],
    "rational-tokens": [
        875,
        10,
        153,
        10387,
        156,
        1591,
        14,
        33,
        109,
        55
    ],
    "importance-scores": [
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN,
        NaN
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "KoboldAI/OPT-6.7B-Erebus",
            "cache_dir": "cache/",
            "tokenizer": "KoboldAI/OPT-6.7B-Erebus",
            "data_dir": "data/analogies/OPT6B/",
            "importance_results_dir": "rationalization_results/analogies/OPT6B_ours/top3_replace0.3_max3000_batch5",
            "device": "cuda",
            "rationalization_config": "config/OPT6B/top3_replace0.3_max3000_batch5.json",
            "input_num_ratio": 1.0,
            "logfolder": "logs/analogies/OPT6B_ours/top3_replace0.3_max3000_batch5",
            "loglevel": 20
        },
        "time_elapsed": 1455.8074598312378,
        "separate_rational": [
            [
                " any",
                " do",
                ").",
                " nerve",
                " (",
                " made",
                " have",
                " million"
            ],
            [
                " nerve",
                "ched",
                " checked",
                " to",
                " more",
                " that",
                " do",
                " a"
            ],
            [
                " wrote",
                " a",
                " pin",
                " to",
                " that",
                " note",
                " more",
                " have"
            ],
            [
                " more",
                " today",
                " a",
                " a",
                " I",
                " to",
                " wrote",
                " note"
            ],
            [
                " note",
                " do",
                " made",
                "Although",
                "'t",
                " so",
                " out",
                " million"
            ]
        ]
    }
}

=== casszhao/ReAGent/rationalization_results/analogies/gpt2_xl_ours/top3_replace0.1_max5000_batch5/122.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 122,
    "input-text": [
        "I",
        " thought",
        " it",
        " would",
        " be",
        " the",
        " simplest",
        " thing",
        " I",
        "'d",
        " ever",
        " encounter",
        ".",
        " (",
        "I",
        " tried",
        " to",
        " ignore",
        " my",
        " phone",
        " vibr",
        "ating",
        " in",
        " my",
        " pocket",
        ").",
        " But",
        " when",
        " I",
        " did",
        " end",
        " up",
        " encountering",
        " it",
        ",",
        " it",
        " turned",
        " out",
        " it",
        " wasn",
        "'t",
        " so"
    ],
    "input-tokens": [
        40,
        1807,
        340,
        561,
        307,
        262,
        24043,
        1517,
        314,
        1549,
        1683,
        8791,
        13,
        357,
        40,
        3088,
        284,
        8856,
        616,
        3072,
        12611,
        803,
        287,
        616,
        10000,
        737,
        887,
        618,
        314,
        750,
        886,
        510,
        42398,
        340,
        11,
        340,
        2900,
        503,
        340,
        2492,
        470,
        523
    ],
    "target-text": " simple",
    "target-token": 2829,
    "rational-size": 11,
    "rational-positions": [
        6,
        10,
        15,
        20,
        30,
        32,
        37,
        38,
        39,
        40,
        41
    ],
    "rational-text": [
        " simplest",
        " ever",
        " tried",
        " vibr",
        " end",
        " encountering",
        " out",
        " it",
        " wasn",
        "'t",
        " so"
    ],
    "rational-tokens": [
        24043,
        1683,
        3088,
        12611,
        886,
        42398,
        503,
        340,
        2492,
        470,
        523
    ],
    "importance-scores": [
        2.2535150492331013e-05,
        8.813132808427326e-06,
        1.6097346815513447e-05,
        2.98772897622257e-06,
        1.0734902389231138e-05,
        3.73041802959051e-05,
        0.24205629527568817,
        1.293282002734486e-05,
        1.8618200556375086e-05,
        0.00014763169747311622,
        0.001972503960132599,
        8.927217095333617e-06,
        1.0056532119051553e-05,
        0.0017262116307392716,
        1.442093798686983e-05,
        0.00019072303257416934,
        0.00017860488151200116,
        2.699388915061718e-06,
        5.400334543992358e-07,
        0.00010439751349622384,
        0.0002933467330876738,
        1.4901817849022336e-05,
        6.306970590230776e-07,
        4.419836841407232e-06,
        1.7696336726658046e-05,
        1.6514011804247275e-05,
        0.1856968104839325,
        0.0007541522500105202,
        3.176687823724933e-05,
        0.19533053040504456,
        0.0014662591274827719,
        0.0018628652906045318,
        0.00011111852654721588,
        1.1687959158734884e-05,
        4.0299013903677405e-07,
        0.003440842032432556,
        0.010782593861222267,
        0.00042122596642002463,
        0.011585782282054424,
        0.00015898968558758497,
        0.11037920415401459,
        0.2310752421617508
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "gpt2-xl",
            "cache_dir": "cache/",
            "tokenizer": "gpt2-xl",
            "data_dir": "data/analogies/gpt2_xl",
            "importance_results_dir": "rationalization_results/analogies/gpt2_xl_ours/top3_replace0.1_max5000_batch5",
            "device": "cuda",
            "rationalization_config": "config//top3_replace0.1_max5000_batch5.json",
            "input_num_ratio": 1.0,
            "logfolder": "logs/analogies/gpt2_xl_ours/top3_replace0.1_max5000_batch5",
            "loglevel": 20
        },
        "time_elapsed": 20.350032567977905,
        "separate_rational": [
            [
                " so",
                " turned",
                " it",
                " simplest",
                "'t",
                " end",
                " to",
                " tried"
            ],
            [
                "'t",
                " so",
                " simplest",
                " ever",
                " (",
                " out",
                " tried",
                " encountering"
            ],
            [
                " did",
                " end",
                " so",
                " when",
                " simplest",
                " vibr",
                " wasn",
                " ever"
            ],
            [
                " But",
                " it",
                " so",
                "'t",
                " up",
                " simplest",
                " it",
                " out"
            ],
            [
                " simplest",
                " wasn",
                "'t",
                " so",
                "ating",
                " vibr",
                " encountering",
                " thing"
            ]
        ]
    }
}

=== casszhao/ReAGent/rationalization_results/analogies/gpt2_xl_gradient_shap/24.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 24,
    "input-text": [
        "When",
        " my",
        " flight",
        " landed",
        " in",
        " Iraq",
        ",",
        " I",
        " converted",
        " my",
        " currency",
        " and",
        " slowly",
        " fell",
        " asleep",
        ".",
        " (",
        "I",
        " was",
        " behind",
        " on",
        " a",
        " couple",
        " of",
        " assignments",
        ",",
        " but",
        " I",
        " tried",
        " not",
        " to",
        " think",
        " about",
        " them",
        ").",
        " I",
        " was",
        " staying",
        " in",
        " the",
        " capital",
        ","
    ],
    "input-tokens": [
        2215,
        616,
        5474,
        11406,
        287,
        3908,
        11,
        314,
        11513,
        616,
        7395,
        290,
        6364,
        3214,
        16039,
        13,
        357,
        40,
        373,
        2157,
        319,
        257,
        3155,
        286,
        25815,
        11,
        475,
        314,
        3088,
        407,
        284,
        892,
        546,
        606,
        737,
        314,
        373,
        10589,
        287,
        262,
        3139,
        11
    ],
    "target-text": " Baghdad",
    "target-token": 19761,
    "rational-size": 5,
    "rational-positions": [
        40,
        5,
        2,
        37,
        3
    ],
    "rational-text": [
        " capital",
        " Iraq",
        " flight",
        " staying",
        " landed"
    ],
    "rational-tokens": [
        3139,
        3908,
        5474,
        10589,
        11406
    ],
    "importance-scores": [
        0.04801291227340698,
        0.0372532457113266,
        0.080111563205719,
        0.05187012255191803,
        0.022092964500188828,
        0.1169930174946785,
        0.006226635072380304,
        0.00671808747574687,
        0.024549979716539383,
        0.009014205075800419,
        0.02960161678493023,
        0.007478700019419193,
        0.0158830676227808,
        0.01135996077209711,
        0.02636834606528282,
        0.008395594544708729,
        0.012592274695634842,
        0.00621177488937974,
        0.006035177502781153,
        0.009087310172617435,
        0.004438926000148058,
        0.0038876065518707037,
        0.016958165913820267,
        0.0054826741106808186,
        0.045091692358255386,
        0.004788885358721018,
        0.009160498157143593,
        0.005930325016379356,
        0.013791028410196304,
        0.007132240571081638,
        0.005108680110424757,
        0.013392694294452667,
        0.009485268034040928,
        0.012784752994775772,
        0.034448545426130295,
        0.012284886091947556,
        0.013265200890600681,
        0.0530063770711422,
        0.0125710004940629,
        0.014547356404364109,
        0.14317789673805237,
        0.023408669978380203
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "gpt2-xl",
            "cache_dir": "./cache/",
            "tokenizer": "gpt2-xl",
            "data_dir": "data/analogies/gpt2_xl/",
            "importance_results_dir": "rationalization_results/analogies/gpt2_xl_gradient_shap",
            "device": "cuda",
            "rationalization_config": "config/eva_gradient_shap.json",
            "input_num_ratio": 1,
            "logfolder": "logs/analogies/gpt2_xl_gradient_shap",
            "loglevel": 20
        },
        "time_elapsed": 0.19620084762573242
    }
}

=== casszhao/ReAGent/rationalization_results/analogies/gpt2_xl_integrated_gradients/54.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 54,
    "input-text": [
        "When",
        " my",
        " flight",
        " landed",
        " in",
        " Chile",
        ",",
        " I",
        " converted",
        " my",
        " currency",
        " and",
        " slowly",
        " fell",
        " asleep",
        ".",
        " (",
        "I",
        " was",
        " behind",
        " on",
        " a",
        " couple",
        " of",
        " assignments",
        ",",
        " but",
        " I",
        " tried",
        " not",
        " to",
        " think",
        " about",
        " them",
        ").",
        " I",
        " was",
        " staying",
        " in",
        " the",
        " capital",
        ","
    ],
    "input-tokens": [
        2215,
        616,
        5474,
        11406,
        287,
        17456,
        11,
        314,
        11513,
        616,
        7395,
        290,
        6364,
        3214,
        16039,
        13,
        357,
        40,
        373,
        2157,
        319,
        257,
        3155,
        286,
        25815,
        11,
        475,
        314,
        3088,
        407,
        284,
        892,
        546,
        606,
        737,
        314,
        373,
        10589,
        287,
        262,
        3139,
        11
    ],
    "target-text": " Santiago",
    "target-token": 34802,
    "rational-size": 5,
    "rational-positions": [
        40,
        5,
        3,
        37,
        2
    ],
    "rational-text": [
        " capital",
        " Chile",
        " landed",
        " staying",
        " flight"
    ],
    "rational-tokens": [
        3139,
        17456,
        11406,
        10589,
        5474
    ],
    "importance-scores": [
        0.02537328191101551,
        0.018021447584033012,
        0.03311045467853546,
        0.03684530407190323,
        0.016444800421595573,
        0.14044012129306793,
        0.009641135111451149,
        0.007852642796933651,
        0.02323201112449169,
        0.00916155707091093,
        0.020572680979967117,
        0.00815465860068798,
        0.01570410281419754,
        0.013813582248985767,
        0.021253541111946106,
        0.009451904334127903,
        0.008719916455447674,
        0.007643597200512886,
        0.00776127353310585,
        0.009672067128121853,
        0.005344175733625889,
        0.004913195967674255,
        0.016247043386101723,
        0.010162736289203167,
        0.029147490859031677,
        0.006965326145291328,
        0.009117704816162586,
        0.00724917184561491,
        0.016057221218943596,
        0.007666764315217733,
        0.005277394317090511,
        0.014570223167538643,
        0.009982596151530743,
        0.014349334873259068,
        0.02058161422610283,
        0.012050852179527283,
        0.012489700689911842,
        0.036613829433918,
        0.01050807349383831,
        0.010705727152526379,
        0.2904333174228668,
        0.0066965543664991856
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "gpt2-xl",
            "cache_dir": "./cache/",
            "tokenizer": "gpt2-xl",
            "data_dir": "data/analogies/gpt2_xl/",
            "importance_results_dir": "rationalization_results/analogies/gpt2_xl_integrated_gradients",
            "device": "cuda",
            "rationalization_config": "config/eva_integrated_gradients.json",
            "input_num_ratio": 1,
            "logfolder": "logs/analogies/gpt2_xl_integrated_gradients",
            "loglevel": 20
        },
        "time_elapsed": 0.9838216304779053
    }
}

=== casszhao/ReAGent/rationalization_results/analogies/gpt2_ours/top3_replace0.3_max3000_batch10/80.json
{
    "$schema": "../docs/rationalization.schema.json",
    "id": 80,
    "input-text": [
        "I",
        " initially",
        " invited",
        " my",
        " sons",
        ",",
        " who",
        " gladly",
        " accepted",
        " my",
        " invitation",
        ".",
        " (",
        "My",
        " favorite",
        " song",
        " just",
        " came",
        " on",
        ",",
        " so",
        " I",
        " was",
        " able",
        " to",
        " relax",
        ").",
        " When",
        " I",
        " learned",
        " that",
        " women",
        " were",
        " allowed",
        ",",
        " I",
        " went",
        " ahead",
        " and",
        " also",
        " invited",
        " my"
    ],
    "input-tokens": [
        40,
        7317,
        9392,
        616,
        11989,
        11,
        508,
        35092,
        6292,
        616,
        17023,
        13,
        357,
        3666,
        4004,
        3496,
        655,
        1625,
        319,
        11,
        523,
        314,
        373,
        1498,
        284,
        8960,
        737,
        1649,
        314,
        4499,
        326,
        1466,
        547,
        3142,
        11,
        314,
        1816,
        4058,
        290,
        635,
        9392,
        616
    ],
    "target-text": " daughters",
    "target-token": 14850,
    "rational-size": 11,
    "rational-positions": [
        0,
        4,
        6,
        7,
        13,
        16,
        23,
        31,
        39,
        40,
        41
    ],
    "rational-text": [
        "I",
        " sons",
        " who",
        " gladly",
        "My",
        " just",
        " able",
        " women",
        " also",
        " invited",
        " my"
    ],
    "rational-tokens": [
        40,
        11989,
        508,
        35092,
        3666,
        655,
        1498,
        1466,
        635,
        9392,
        616
    ],
    "importance-scores": [
        0.008069973438978195,
        0.021784871816635132,
        0.0020478994119912386,
        0.005181724205613136,
        0.15526340901851654,
        0.00197143224067986,
        0.01641141250729561,
        0.045706626027822495,
        0.0014292161213234067,
        0.017981169745326042,
        0.007563511375337839,
        0.0070470585487782955,
        0.08845767378807068,
        0.006255181971937418,
        0.019710127264261246,
        0.001768631860613823,
        0.005865485407412052,
        0.0029269319493323565,
        0.0018706010887399316,
        0.007347357925027609,
        0.003566515166312456,
        0.002112173242494464,
        0.01975323259830475,
        0.001358816516585648,
        0.002465927042067051,
        0.003169124247506261,
        0.004035186022520065,
        0.005864331964403391,
        0.012011023238301277,
        0.00205812300555408,
        0.0034238812513649464,
        0.007253145333379507,
        0.0016780814621597528,
        0.08316043764352798,
        0.0152354184538126,
        0.002563648857176304,
        0.0078668761998415,
        0.0030791277531534433,
        0.0035103417467325926,
        0.002805711468681693,
        0.21077442169189453,
        0.1775941550731659
    ],
    "comments": {
        "created-by": "run_analogies.py",
        "args": {
            "model": "gpt2-medium",
            "cache_dir": "cache/",
            "tokenizer": "gpt2-medium",
            "data_dir": "data/analogies/gpt2",
            "importance_results_dir": "rationalization_results/analogies/gpt2_ours/top3_replace0.3_max3000_batch10",
            "device": "cuda",
            "rationalization_config": "config//top3_replace0.3_max3000_batch10.json",
            "input_num_ratio": 1.0,
            "logfolder": "logs/analogies/gpt2_ours/top3_replace0.3_max3000_batch10",
            "loglevel": 20
        },
        "time_elapsed": 186.00983786582947,
        "separate_rational": [
            [
                " initially",
                " favorite",
                " my",
                " sons",
                " who"
            ],
            [
                " sons",
                " When",
                " my",
                " women",
                " also"
            ],
            [
                " gladly",
                " was",
                ",",
                " sons",
                ","
            ],
            [
                " allowed",
                " I",
                " sons",
                "I",
                " invited"
            ],
            [
                " my",
                " sons",
                " invited",
                " women",
                " so"
            ],
            [
                " invited",
                " that",
                " just",
                " able",
                " sons"
            ],
            [
                " my",
                " sons",
                " song",
                " women",
                " also"
            ],
            [
                " invited",
                " able",
                "My",
                " sons",
                " came"
            ],
            [
                " (",
                " gladly",
                " women",
                " invited",
                " sons"
            ],
            [
                " who",
                " sons",
                " just",
                "My",
                "I"
            ]
        ]
    }
}
